#!/usr/bin/env python3
"""Scheme of Things — ordinary engineering, slot 26 (Reversing, H0).

Deterministic generator for a medium reverse-engineering challenge:
a stripped ELF that evaluates a serialized Scheme-like AST hidden in an
encoded .rodata blob. The passphrase is never compared as a string; the
flag is stream-XOR sealed behind FNV-1a(passphrase) and only revealed
when the hidden expression evaluates true.

Adapted from the CyberQuest `the_evaluator_lies` generator to the
ordinary engineering format: cyber_quest{} flags, corporate-lore copy,
and the 2026 handout zip convention.
"""
import argparse
import base64
import json
import os
import random
import shutil
import struct
import subprocess
import zipfile
from pathlib import Path

OPS = ["length", "char", "add", "xor", "rol8", "mod", "eq", "and", "if", "sub", "or", "not"]


def rol8(v, r):
    r &= 7
    return ((v << r) | (v >> (8-r))) & 0xff if r else v & 0xff


def fnv1a64(data: bytes) -> int:
    h = 0xcbf29ce484222325
    for b in data:
        h ^= b
        h = (h * 0x100000001b3) & 0xffffffffffffffff
    return h


def xorshift64star(x: int) -> int:
    x ^= (x >> 12) & 0xffffffffffffffff
    x ^= (x << 25) & 0xffffffffffffffff
    x ^= (x >> 27) & 0xffffffffffffffff
    return x & 0xffffffffffffffff


def crypt_flag(flag: bytes, password: bytes, salt: int) -> bytes:
    state = fnv1a64(password) ^ salt
    out = bytearray()
    for b in flag:
        state = xorshift64star(state)
        z = (state * 0x2545F4914F6CDD1D) & 0xffffffffffffffff
        out.append(b ^ ((z >> 56) & 0xff))
    return bytes(out)


# AST constructors ---------------------------------------------------------
def I(n): return ("int", int(n))
def B(v): return ("bool", bool(v))
def S(name): return ("sym", name)
def C(name, *args): return ("list", [S(name), *args])


def make_ast(password: bytes, rng: random.Random):
    constraints = []
    per_char = []
    for i, ch in enumerate(password):
        shift = rng.randint(1, 7)
        mask = rng.randint(1, 255)
        bias = rng.randint(0, 255)
        target = (rol8(ch, shift) ^ mask)
        target = (target + bias) & 0xff
        expr = C("mod", C("add", C("xor", C("rol8", C("char", I(i)), I(shift)), I(mask)), I(bias)), I(256))
        constraints.append(C("eq", expr, I(target)))
        per_char.append({"index": i, "shift": shift, "mask": mask, "bias": bias, "target": target})

    # Pairwise constraints are redundant but add useful noise and confirm ordering.
    pairs = []
    for i in range(0, max(0, len(password)-1), 3):
        j = i + 1
        if j >= len(password):
            break
        bias = rng.randint(1, 250)
        target = (password[i] + password[j] + bias) % 257
        constraints.append(C("eq", C("mod", C("add", C("char", I(i)), C("char", I(j)), I(bias)), I(257)), I(target)))
        pairs.append({"i": i, "j": j, "bias": bias, "target": target})

    # Dead branches: syntactically valid constraints that are never evaluated.
    dead = []
    for _ in range(max(2, len(password)//4)):
        idx = rng.randrange(len(password)) if password else 0
        fake = C("eq", C("xor", C("char", I(idx)), I(rng.randint(0,255))), I(rng.randint(0,255)))
        if rng.choice([True, False]):
            dead.append(C("if", B(False), fake, B(True)))
        else:
            dead.append(C("if", B(True), B(True), fake))

    rng.shuffle(constraints)
    rng.shuffle(dead)
    exprs = [C("eq", C("length"), I(len(password)))] + constraints + dead
    rng.shuffle(exprs)
    return C("and", *exprs), per_char, pairs


def serialize_ast(node, kind_tags, sym_ids):
    kind = node[0]
    if kind == "int":
        return bytes([kind_tags["int"]]) + struct.pack("<i", node[1])
    if kind == "bool":
        return bytes([kind_tags["bool"], 1 if node[1] else 0])
    if kind == "sym":
        return bytes([kind_tags["sym"]]) + struct.pack("<H", sym_ids[node[1]])
    if kind == "list":
        items = node[1]
        if len(items) > 255:
            raise ValueError("AST list too large")
        return bytes([kind_tags["list"], len(items)]) + b"".join(serialize_ast(x, kind_tags, sym_ids) for x in items)
    raise ValueError(kind)


def encode_blob(raw: bytes, a: int, b: int, c: int) -> bytes:
    out = bytearray()
    for i, x in enumerate(raw):
        t = ((i * a + b) & 0xff)
        u = (i + c) & 0xff
        u = rol8(u, 3)
        out.append(x ^ t ^ u)
    return bytes(out)


def c_array(data: bytes, width=12):
    parts = [f"0x{x:02x}" for x in data]
    return ",\n    ".join(", ".join(parts[i:i+width]) for i in range(0, len(parts), width))


def emit_c(encoded_ast, encrypted_flag, kind_tags, sym_ids, a, b, c, salt):
    sid = {k: sym_ids[k] for k in OPS}
    return fr'''// Generated by deployment/generate.py (ordinary engineering, slot 26).
// Organizer source; distribute the binary, not this file.
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define TAG_INT  {kind_tags["int"]}
#define TAG_BOOL {kind_tags["bool"]}
#define TAG_SYM  {kind_tags["sym"]}
#define TAG_LIST {kind_tags["list"]}

#define S_LENGTH {sid["length"]}
#define S_CHAR   {sid["char"]}
#define S_ADD    {sid["add"]}
#define S_XOR    {sid["xor"]}
#define S_ROL8   {sid["rol8"]}
#define S_MOD    {sid["mod"]}
#define S_EQ     {sid["eq"]}
#define S_AND    {sid["and"]}
#define S_IF     {sid["if"]}
#define S_SUB    {sid["sub"]}
#define S_OR     {sid["or"]}
#define S_NOT    {sid["not"]}

#define ENC_A {a}
#define ENC_B {b}
#define ENC_C {c}
#define FLAG_SALT UINT64_C(0x{salt:016x})

static const uint8_t program_blob[] = {{
    {c_array(encoded_ast)}
}};
static const size_t program_blob_len = sizeof(program_blob);

static const uint8_t flag_cipher[] = {{
    {c_array(encrypted_flag)}
}};
static const size_t flag_cipher_len = sizeof(flag_cipher);

// Deliberate semantic noise. These strings are not the hidden program.
__attribute__((used)) static const char *decoy_words[] = {{
    "lambda", "quote", "cons", "car", "cdr", "strcmp", "debug_win", "flag.txt", "admin=true"
}};

typedef enum {{ N_INT, N_BOOL, N_SYM, N_LIST }} NodeKind;
typedef struct Node Node;
struct Node {{
    NodeKind kind;
    int32_t iv;
    uint16_t sym;
    uint8_t count;
    Node **items;
}};

typedef struct {{ size_t off; int failed; }} Reader;

static uint8_t rol8(uint8_t x, unsigned r) {{
    r &= 7;
    return r ? (uint8_t)((x << r) | (x >> (8-r))) : x;
}}

static uint8_t dec_at(size_t i) {{
    uint8_t t = (uint8_t)(i * ENC_A + ENC_B);
    uint8_t u = rol8((uint8_t)(i + ENC_C), 3);
    return program_blob[i] ^ t ^ u;
}}

static uint8_t rd8(Reader *r) {{
    if (r->off >= program_blob_len) {{ r->failed = 1; return 0; }}
    return dec_at(r->off++);
}}
static uint16_t rd16(Reader *r) {{
    uint16_t a = rd8(r), b = rd8(r);
    return (uint16_t)(a | (b << 8));
}}
static int32_t rd32(Reader *r) {{
    uint32_t v = 0;
    for (unsigned i=0;i<4;i++) v |= ((uint32_t)rd8(r)) << (8*i);
    return (int32_t)v;
}}

static Node *node_new(void) {{
    Node *n = (Node*)calloc(1, sizeof(Node));
    if (!n) exit(2);
    return n;
}}

static Node *parse_node(Reader *r, unsigned depth) {{
    if (depth > 128 || r->failed) {{ r->failed = 1; return NULL; }}
    uint8_t tag = rd8(r);
    Node *n = node_new();
    if (tag == TAG_INT) {{ n->kind=N_INT; n->iv=rd32(r); return n; }}
    if (tag == TAG_BOOL) {{ n->kind=N_BOOL; n->iv=(rd8(r)!=0); return n; }}
    if (tag == TAG_SYM) {{ n->kind=N_SYM; n->sym=rd16(r); return n; }}
    if (tag == TAG_LIST) {{
        n->kind=N_LIST;
        n->count=rd8(r);
        n->items=(Node**)calloc(n->count ? n->count : 1, sizeof(Node*));
        if (!n->items) exit(2);
        for (unsigned i=0;i<n->count;i++) n->items[i]=parse_node(r, depth+1);
        return n;
    }}
    r->failed=1;
    return n;
}}

static void free_node(Node *n) {{
    if (!n) return;
    if (n->kind == N_LIST) {{
        for (unsigned i=0;i<n->count;i++) free_node(n->items[i]);
        free(n->items);
    }}
    free(n);
}}

static int64_t eval(Node *n, const uint8_t *input, size_t input_len, int *ok);

static int64_t arg(Node *n, unsigned idx, const uint8_t *input, size_t input_len, int *ok) {{
    if (!n || n->kind != N_LIST || idx >= n->count) {{ *ok=0; return 0; }}
    return eval(n->items[idx], input, input_len, ok);
}}

static int64_t eval(Node *n, const uint8_t *input, size_t input_len, int *ok) {{
    if (!n || !*ok) return 0;
    if (n->kind == N_INT || n->kind == N_BOOL) return n->iv;
    if (n->kind == N_SYM) {{ *ok=0; return 0; }}
    if (n->count == 0 || n->items[0]->kind != N_SYM) {{ *ok=0; return 0; }}
    uint16_t op = n->items[0]->sym;

    if (op == S_LENGTH) return (int64_t)input_len;
    if (op == S_CHAR) {{
        int64_t i = arg(n,1,input,input_len,ok);
        if (!*ok || i < 0 || (uint64_t)i >= input_len) return -4096;
        return input[i];
    }}
    if (op == S_ADD) {{
        int64_t v=0; for (unsigned i=1;i<n->count;i++) v += arg(n,i,input,input_len,ok); return v;
    }}
    if (op == S_SUB) {{
        if (n->count < 2) {{ *ok=0; return 0; }}
        int64_t v=arg(n,1,input,input_len,ok); for (unsigned i=2;i<n->count;i++) v -= arg(n,i,input,input_len,ok); return v;
    }}
    if (op == S_XOR) return arg(n,1,input,input_len,ok) ^ arg(n,2,input,input_len,ok);
    if (op == S_ROL8) return rol8((uint8_t)arg(n,1,input,input_len,ok), (unsigned)arg(n,2,input,input_len,ok));
    if (op == S_MOD) {{
        int64_t a=arg(n,1,input,input_len,ok), m=arg(n,2,input,input_len,ok);
        if (!*ok || m==0) {{ *ok=0; return 0; }}
        int64_t z=a%m; return z<0?z+m:z;
    }}
    if (op == S_EQ) return arg(n,1,input,input_len,ok) == arg(n,2,input,input_len,ok);
    if (op == S_AND) {{
        for (unsigned i=1;i<n->count;i++) if (!arg(n,i,input,input_len,ok)) return 0;
        return *ok ? 1 : 0;
    }}
    if (op == S_OR) {{
        for (unsigned i=1;i<n->count;i++) if (arg(n,i,input,input_len,ok)) return 1;
        return 0;
    }}
    if (op == S_NOT) return !arg(n,1,input,input_len,ok);
    if (op == S_IF) {{
        int64_t cond=arg(n,1,input,input_len,ok);
        return cond ? arg(n,2,input,input_len,ok) : arg(n,3,input,input_len,ok);
    }}
    *ok=0;
    return 0;
}}

static uint64_t fnv1a64(const uint8_t *p, size_t n) {{
    uint64_t h=UINT64_C(0xcbf29ce484222325);
    for (size_t i=0;i<n;i++) {{ h ^= p[i]; h *= UINT64_C(0x100000001b3); }}
    return h;
}}
static uint64_t xs64(uint64_t x) {{ x ^= x>>12; x ^= x<<25; x ^= x>>27; return x; }}

static void reveal(const uint8_t *input, size_t n) {{
    uint64_t st = fnv1a64(input,n) ^ FLAG_SALT;
    for (size_t i=0;i<flag_cipher_len;i++) {{
        st = xs64(st);
        uint64_t z = st * UINT64_C(0x2545F4914F6CDD1D);
        putchar((int)(flag_cipher[i] ^ (uint8_t)(z >> 56)));
    }}
    putchar('\n');
}}

int main(void) {{
    char buf[256];
    puts("oe-evaluator // calibration build");
    puts("The evaluator does not ask what you typed. It asks what the expression becomes.");
    fputs("passphrase> ", stdout);
    fflush(stdout);
    if (!fgets(buf,sizeof(buf),stdin)) return 1;
    size_t n=strcspn(buf,"\r\n");
    buf[n]='\0';

    Reader r={{0,0}};
    Node *root=parse_node(&r,0);
    int ok=!r.failed && r.off==program_blob_len;
    int64_t accepted = ok ? eval(root,(const uint8_t*)buf,n,&ok) : 0;
    if (ok && accepted) reveal((const uint8_t*)buf,n);
    else puts("Input does not satisfy the current evaluation policy. Incident logged.");
    free_node(root);
    return 0;
}}
'''


def emit_reference_solver(meta):
    # This is an organizer-side verifier / intended-math demonstration, not distributed.
    rows = meta["per_char"]
    return f'''#!/usr/bin/env python3
# Organizer reference solve. Reconstructs the passphrase from the generated
# constraints (deployment/organizer/metadata.json). Not distributed to players.

import json
import sys


def ror8(v, r):
    r &= 7
    return ((v >> r) | ((v << (8-r)) & 0xff)) & 0xff if r else v & 0xff


meta = json.load(open(sys.argv[1] if len(sys.argv) > 1 else "metadata.json"))
rows = meta["per_char"]
out = []
for row in sorted(rows, key=lambda x: x["index"]):
    y = (row["target"] - row["bias"]) & 0xff
    y ^= row["mask"]
    out.append(ror8(y, row["shift"]))
print(bytes(out).decode("utf-8"))
'''


def main():
    ap = argparse.ArgumentParser(description="Generate the Scheme of Things RE challenge (ordinary engineering, slot 26)")
    ap.add_argument("--seed", default="oe-scheme-of-things-26")
    ap.add_argument("--password", default="structure_not_syntax")
    ap.add_argument("--flag", default="cyber_quest{struktur3_n0t_str1ngs_9c4e7a}")
    ap.add_argument("--out", default="build_scheme_of_things")
    ap.add_argument("--no-build", action="store_true")
    args = ap.parse_args()

    password = args.password.encode()
    flag = args.flag.encode()
    if not (4 <= len(password) <= 80):
        raise SystemExit("password must be 4..80 bytes")
    if len(flag) > 200:
        raise SystemExit("flag too long")

    rng = random.Random(args.seed)
    out = Path(args.out).resolve()
    if out.exists(): shutil.rmtree(out)
    player = out / "player"
    org = out / "organizer"
    player.mkdir(parents=True)
    org.mkdir(parents=True)

    # Randomize AST type tags and symbol IDs per seed.
    tags = rng.sample(range(0x21,0xf0),4)
    kind_tags = dict(zip(["int","bool","sym","list"], tags))
    ids = rng.sample(range(0x0100,0xff00), len(OPS))
    sym_ids = dict(zip(OPS, ids))

    ast, per_char, pairs = make_ast(password, rng)
    raw = serialize_ast(ast, kind_tags, sym_ids)

    # Keep A odd so the byte pattern has no tiny obvious period.
    a = rng.randrange(1,256,2)
    b = rng.randrange(0,256)
    c = rng.randrange(0,256)
    encoded = encode_blob(raw,a,b,c)
    salt = rng.getrandbits(64)
    enc_flag = crypt_flag(flag,password,salt)

    csrc = emit_c(encoded,enc_flag,kind_tags,sym_ids,a,b,c,salt)
    (org/"challenge.c").write_text(csrc)
    (org/"Makefile").write_text("""CC ?= gcc\nCFLAGS ?= -std=c11 -O1 -fno-inline -fno-ident -Wall -Wextra\nall: evaluator\nevaluator: challenge.c\n\t$(CC) $(CFLAGS) challenge.c -o evaluator\nstrip:\n\tstrip evaluator\nclean:\n\trm -f evaluator\n""")

    meta = {
        "seed": args.seed,
        "password": args.password,
        "flag": args.flag,
        "kind_tags": kind_tags,
        "symbol_ids": sym_ids,
        "encoding": {"a":a,"b":b,"c":c},
        "ast_raw_b64": base64.b64encode(raw).decode(),
        "ast_encoded_b64": base64.b64encode(encoded).decode(),
        "per_char": per_char,
        "pair_constraints": pairs,
        "flag_salt": f"0x{salt:016x}",
        "flag_cipher_hex": enc_flag.hex(),
    }
    (org/"metadata.json").write_text(json.dumps(meta,indent=2))
    (org/"solve_reference.py").write_text(emit_reference_solver(meta))
    os.chmod(org/"solve_reference.py",0o755)

    player_readme = '''oe-evaluator

Performance calibration season. The evaluation tool that arrived with
the Q3 import batch has rejected every passphrase IT Support has on
file, and it is the only thing standing between you and your review
file. The vendor documentation is one page and mostly warranty
disclaimers.

A note taped to the kiosk, in someone's handwriting:

    The evaluator does not ask what you typed.
    It asks what the expression becomes.

Recover the passphrase. The tool prints the rest once an evaluation
passes.
'''
    (player/"README.txt").write_text(player_readme)

    if not args.no_build:
        subprocess.run(["gcc","-std=c11","-O1","-fno-inline","-fno-ident","-Wall","-Wextra",str(org/"challenge.c"),"-o",str(player/"evaluator")],check=True)
        if shutil.which("strip"):
            subprocess.run(["strip",str(player/"evaluator")],check=True)
        # Positive and negative tests.
        p = subprocess.run([str(player/"evaluator")],input=(args.password+"\n").encode(),stdout=subprocess.PIPE,stderr=subprocess.PIPE,check=True)
        if args.flag.encode() not in p.stdout:
            raise SystemExit("self-test failed: correct passphrase did not reveal flag")
        p2 = subprocess.run([str(player/"evaluator")],input=b"definitely-wrong\n",stdout=subprocess.PIPE,stderr=subprocess.PIPE,check=True)
        if args.flag.encode() in p2.stdout:
            raise SystemExit("self-test failed: wrong passphrase revealed flag")

    # Pack only player distributables.
    bundle = out / "26_scheme_of_things.zip"
    with zipfile.ZipFile(bundle,"w",zipfile.ZIP_DEFLATED) as zf:
        for p in player.iterdir():
            zf.write(p, arcname=p.name)

    print(f"Generated: {out}")
    print(f"Player bundle: {bundle}")
    print(f"Organizer source: {org/'challenge.c'}")
    print(f"Reference solver: {org/'solve_reference.py'}")


if __name__ == "__main__":
    main()
