#!/usr/bin/env python3
"""Encrypt the two position-independent stage .text blobs."""

from __future__ import annotations

import argparse
import random
from pathlib import Path

SEED = 0x4242


def c_array(name: str, data: bytes) -> str:
    rows = []
    for start in range(0, len(data), 16):
        row = ", ".join(f"0x{byte:02x}" for byte in data[start : start + 16])
        rows.append(f"    {row}")
    return f"static const unsigned char {name}[{len(data)}] = {{\n" + \
        ",\n".join(rows) + "\n};"


def xor_key(rng: random.Random, length: int) -> bytes:
    return bytes(rng.randrange(1, 256) for _ in range(length))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--stage-a", type=Path, required=True)
    parser.add_argument("--stage-c", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    stage_a = args.stage_a.read_bytes()
    stage_c = args.stage_c.read_bytes()
    if not stage_a or not stage_c:
        raise SystemExit("stage extraction produced an empty .text blob")
    if max(len(stage_a), len(stage_c)) > 4096:
        raise SystemExit("stage is larger than one executable page")

    rng = random.Random(SEED)
    key_a = xor_key(rng, len(stage_a))
    key_c = xor_key(rng, len(stage_c))
    enc_a = bytes(byte ^ key for byte, key in zip(stage_a, key_a))
    enc_c = bytes(byte ^ key for byte, key in zip(stage_c, key_c))

    content = """/* generated by gen_stages.py; do not edit by hand */
#ifndef BREAK_GLASS_STAGES_H
#define BREAK_GLASS_STAGES_H

"""
    content += c_array("enc_stage_a", enc_a) + "\n"
    content += c_array("key_stage_a", key_a) + "\n\n"
    content += c_array("enc_stage_c", enc_c) + "\n"
    content += c_array("key_stage_c", key_c) + "\n\n#endif\n"
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="ascii")
    print(f"stage_a={len(stage_a)} bytes stage_c={len(stage_c)} bytes")


if __name__ == "__main__":
    main()
