#!/usr/bin/env python3
"""Generate the encrypted flag fragment used by the release binary."""

from __future__ import annotations

import argparse
from pathlib import Path

FLAG = "cyber_quest{br34k_gl4ss_l1v3_p4tch_7f3a1c}"
EXPECTED_A = 0x442CB715D93C702D
DONE_STATE = 0xFF
SALT = 0xC0FFEE1234567890
MASK64 = (1 << 64) - 1


def mix(value: int) -> int:
    value &= MASK64
    value ^= value >> 33
    value = (value * 0xFF51AFD7ED558CCD) & MASK64
    value ^= value >> 33
    value = (value * 0xC4CEB9FE1A85EC53) & MASK64
    value ^= value >> 33
    return value


def keystream_byte(master_key: int, index: int) -> int:
    return mix(master_key + index * 0x9E3779B97F4A7C15) & 0xFF


def c_array(name: str, data: bytes) -> str:
    rows = []
    for start in range(0, len(data), 16):
        row = ", ".join(f"0x{byte:02x}" for byte in data[start : start + 16])
        rows.append(f"    {row}")
    return f"static const unsigned char {name}[{len(data)}] = {{\n" + \
        ",\n".join(rows) + "\n};"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    inner = FLAG.removeprefix("cyber_quest{").removesuffix("}").encode()
    target_key = EXPECTED_A ^ (DONE_STATE << 32) ^ SALT
    encrypted = bytes(
        byte ^ keystream_byte(target_key, index)
        for index, byte in enumerate(inner)
    )
    decoded = bytes(
        byte ^ keystream_byte(target_key, index)
        for index, byte in enumerate(encrypted)
    )
    if decoded != inner:
        raise SystemExit("flag fragment self-check failed")

    content = """/* generated by gen_frag.py; do not edit by hand */
#ifndef BREAK_GLASS_FRAG_ARRAYS_H
#define BREAK_GLASS_FRAG_ARRAYS_H

"""
    content += c_array("frag_enc", encrypted) + "\n"
    content += f"#define FRAG_LEN {len(inner)}\n"
    content += f"#define GATE_SALT UINT64_C(0x{SALT:016x})\n"
    content += "\n#endif\n"
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="ascii")
    print(f"flag fragment length={len(inner)} bytes target_key=0x{target_key:016x}")


if __name__ == "__main__":
    main()
